[versions]
algoutils = "0.7.2"

[plugins]
algomate = { id = "org.tudalgo.algomate", version = "0.6.1" }
jagr = { id = "org.sourcegrade.jagr-gradle", version = "0.10.2" }

[libraries]
annotations = "org.jetbrains:annotations:23.0.0"
algoutils-student = { module = "org.tudalgo:algoutils-student", version.ref = "algoutils" }
algoutils-tutor = { module = "org.tudalgo:algoutils-tutor", version.ref = "algoutils" }
